### ISSUE TITLE
Top Sign Up Button

### ISSUE THREAD

**Issue by jesspaget** [jesspaget/saas-website#4]
Sign up button at top of page is right placement at XS and S but when I get bigger to M and L it jumps about an inch higher. 

(right placement)
![screen shot 2014-11-26 at 5 37 39 pm](https://cloud.githubusercontent.com/assets/6373211/5209978/1eb2566c-7593-11e4-9ea2-9f68e196fc53.png)

(wrong placement)
![screen shot 2014-11-26 at 5 37 50 pm](https://cloud.githubusercontent.com/assets/6373211/5209983/36e60c7e-7593-11e4-8f31-167ec180eac0.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
There's one thing I can see that may be causing the issue:
https://github.com/jesspaget/saas-website/blob/gh-pages/index.html#L32
There's no such HTML element as `billboard`—change it to a `div`.

---

Then, I had more success getting them to stay in place using pixels instead of ems, like this:

``` css
.sunset {
  padding: 265px 0; /* Used to be ems */
}

.top-button {
  bottom: 360px; /* Used to be ems */
}
```
